# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './py/adcdialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ADCDialog(object):
    def setupUi(self, ADCDialog):
        ADCDialog.setObjectName("ADCDialog")
        ADCDialog.resize(865, 658)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/adc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ADCDialog.setWindowIcon(icon)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ADCDialog)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainWidget = QtWidgets.QWidget(ADCDialog)
        self.mainWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.mainWidget.setObjectName("mainWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chartContainer = QtWidgets.QWidget(self.mainWidget)
        self.chartContainer.setMinimumSize(QtCore.QSize(500, 300))
        self.chartContainer.setStyleSheet("border-color: rgb(6, 6, 6);")
        self.chartContainer.setObjectName("chartContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.chartContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chartCanvasWidget = QtWidgets.QWidget(self.chartContainer)
        self.chartCanvasWidget.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.chartCanvasWidget.setObjectName("chartCanvasWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.chartCanvasWidget)
        self.verticalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout.addWidget(self.chartCanvasWidget)
        self.toolbarCanvasContainer = QtWidgets.QWidget(self.chartContainer)
        self.toolbarCanvasContainer.setAutoFillBackground(False)
        self.toolbarCanvasContainer.setStyleSheet("")
        self.toolbarCanvasContainer.setObjectName("toolbarCanvasContainer")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.toolbarCanvasContainer)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolbarCanvasWidget = QtWidgets.QWidget(self.toolbarCanvasContainer)
        self.toolbarCanvasWidget.setMinimumSize(QtCore.QSize(450, 0))
        self.toolbarCanvasWidget.setObjectName("toolbarCanvasWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.toolbarCanvasWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4.addWidget(self.toolbarCanvasWidget)
        self.verticalLayout.addWidget(self.toolbarCanvasContainer)
        self.horizontalLayout_2.addWidget(self.chartContainer)
        self.verticalLayout_2.addWidget(self.mainWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.controlWidget = QtWidgets.QWidget(ADCDialog)
        self.controlWidget.setObjectName("controlWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.controlWidget)
        self.horizontalLayout.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.controlWidget)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.reloadButton = QtWidgets.QPushButton(self.controlWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reloadButton.setIcon(icon1)
        self.reloadButton.setObjectName("reloadButton")
        self.horizontalLayout.addWidget(self.reloadButton)
        self.exportButton = QtWidgets.QPushButton(self.controlWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/matlab.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exportButton.setIcon(icon2)
        self.exportButton.setObjectName("exportButton")
        self.horizontalLayout.addWidget(self.exportButton)
        self.okButton = QtWidgets.QPushButton(self.controlWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.okButton.setIcon(icon3)
        self.okButton.setObjectName("okButton")
        self.horizontalLayout.addWidget(self.okButton)
        self.verticalLayout_2.addWidget(self.controlWidget)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)

        self.retranslateUi(ADCDialog)
        QtCore.QMetaObject.connectSlotsByName(ADCDialog)

    def retranslateUi(self, ADCDialog):
        _translate = QtCore.QCoreApplication.translate
        ADCDialog.setWindowTitle(_translate("ADCDialog", "ADC Sampler"))
        self.reloadButton.setText(_translate("ADCDialog", "Reload"))
        self.exportButton.setText(_translate("ADCDialog", "Export"))
        self.okButton.setText(_translate("ADCDialog", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ADCDialog = QtWidgets.QDialog()
    ui = Ui_ADCDialog()
    ui.setupUi(ADCDialog)
    ADCDialog.show()
    sys.exit(app.exec_())

