# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './py/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1088, 814)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/inpe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.filterWidget = QtWidgets.QWidget(self.groupBox_2)
        self.filterWidget.setAutoFillBackground(False)
        self.filterWidget.setStyleSheet("border-color: rgb(3, 3, 3);")
        self.filterWidget.setObjectName("filterWidget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.filterWidget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.filterPTTCheckBox = QtWidgets.QCheckBox(self.filterWidget)
        self.filterPTTCheckBox.setChecked(False)
        self.filterPTTCheckBox.setObjectName("filterPTTCheckBox")
        self.horizontalLayout_6.addWidget(self.filterPTTCheckBox)
        self.filterHKCheckBox = QtWidgets.QCheckBox(self.filterWidget)
        self.filterHKCheckBox.setChecked(True)
        self.filterHKCheckBox.setObjectName("filterHKCheckBox")
        self.horizontalLayout_6.addWidget(self.filterHKCheckBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.horizontalLayout_9.addWidget(self.filterWidget)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.mainTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.mainTableWidget.setMinimumSize(QtCore.QSize(500, 300))
        self.mainTableWidget.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.mainTableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.mainTableWidget.setAlternatingRowColors(True)
        self.mainTableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.mainTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.mainTableWidget.setGridStyle(QtCore.Qt.DotLine)
        self.mainTableWidget.setObjectName("mainTableWidget")
        self.mainTableWidget.setColumnCount(4)
        self.mainTableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.mainTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.mainTableWidget.setHorizontalHeaderItem(3, item)
        self.mainTableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.mainTableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.mainTableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.mainTableWidget.horizontalHeader().setStretchLastSection(True)
        self.mainTableWidget.verticalHeader().setVisible(False)
        self.mainTableWidget.verticalHeader().setHighlightSections(False)
        self.mainTableWidget.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.mainTableWidget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.detailToolBox = QtWidgets.QToolBox(self.centralwidget)
        self.detailToolBox.setMinimumSize(QtCore.QSize(0, 200))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.detailToolBox.setFont(font)
        self.detailToolBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.detailToolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.detailToolBox.setObjectName("detailToolBox")
        self.detailPackageBox = QtWidgets.QWidget()
        self.detailPackageBox.setGeometry(QtCore.QRect(0, 0, 652, 269))
        self.detailPackageBox.setMinimumSize(QtCore.QSize(0, 200))
        self.detailPackageBox.setBaseSize(QtCore.QSize(0, 0))
        self.detailPackageBox.setAcceptDrops(False)
        self.detailPackageBox.setObjectName("detailPackageBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.detailPackageBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.treeWidget = QtWidgets.QTreeWidget(self.detailPackageBox)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.treeWidget.setFont(font)
        self.treeWidget.setAlternatingRowColors(True)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        self.treeWidget.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        self.treeWidget.header().setVisible(False)
        self.treeWidget.header().setDefaultSectionSize(200)
        self.treeWidget.header().setMinimumSectionSize(200)
        self.verticalLayout_4.addWidget(self.treeWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("img/detail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detailToolBox.addItem(self.detailPackageBox, icon1, "")
        self.rawDataBox = QtWidgets.QWidget()
        self.rawDataBox.setGeometry(QtCore.QRect(0, 0, 652, 269))
        self.rawDataBox.setMinimumSize(QtCore.QSize(0, 100))
        self.rawDataBox.setObjectName("rawDataBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.rawDataBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rawDataTable = QtWidgets.QTableWidget(self.rawDataBox)
        self.rawDataTable.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rawDataTable.setFont(font)
        self.rawDataTable.setAutoScroll(False)
        self.rawDataTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.rawDataTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.rawDataTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.rawDataTable.setGridStyle(QtCore.Qt.DotLine)
        self.rawDataTable.setObjectName("rawDataTable")
        self.rawDataTable.setColumnCount(3)
        self.rawDataTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.rawDataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rawDataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rawDataTable.setHorizontalHeaderItem(2, item)
        self.rawDataTable.horizontalHeader().setStretchLastSection(True)
        self.rawDataTable.verticalHeader().setVisible(False)
        self.rawDataTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_3.addWidget(self.rawDataTable)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("img/bin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.detailToolBox.addItem(self.rawDataBox, icon2, "")
        self.verticalLayout.addWidget(self.detailToolBox)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.widget_11 = QtWidgets.QWidget(self.centralwidget)
        self.widget_11.setMaximumSize(QtCore.QSize(400, 16777215))
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.controlToolBox = QtWidgets.QToolBox(self.widget_11)
        self.controlToolBox.setMinimumSize(QtCore.QSize(0, 200))
        self.controlToolBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.controlToolBox.setFont(font)
        self.controlToolBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.controlToolBox.setFrameShadow(QtWidgets.QFrame.Plain)
        self.controlToolBox.setObjectName("controlToolBox")
        self.configPage = QtWidgets.QWidget()
        self.configPage.setGeometry(QtCore.QRect(0, 0, 398, 641))
        self.configPage.setObjectName("configPage")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.configPage)
        self.verticalLayout_5.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.connectionConfigWidget = QtWidgets.QWidget(self.configPage)
        self.connectionConfigWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.connectionConfigWidget.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.connectionConfigWidget.setFont(font)
        self.connectionConfigWidget.setObjectName("connectionConfigWidget")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.connectionConfigWidget)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.connectionConfigWidget)
        self.tabWidget_2.setMaximumSize(QtCore.QSize(10000, 10000))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_15 = QtWidgets.QWidget(self.tab_2)
        self.widget_15.setObjectName("widget_15")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_15)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.widget_12 = QtWidgets.QWidget(self.widget_15)
        self.widget_12.setObjectName("widget_12")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget_12)
        self.horizontalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.connSerialRadio = QtWidgets.QRadioButton(self.widget_12)
        self.connSerialRadio.setChecked(True)
        self.connSerialRadio.setObjectName("connSerialRadio")
        self.horizontalLayout_13.addWidget(self.connSerialRadio)
        self.connFtdiRadio = QtWidgets.QRadioButton(self.widget_12)
        self.connFtdiRadio.setObjectName("connFtdiRadio")
        self.horizontalLayout_13.addWidget(self.connFtdiRadio)
        self.widget_14 = QtWidgets.QWidget(self.widget_12)
        self.widget_14.setObjectName("widget_14")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_14)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.comPortComboBox = QtWidgets.QComboBox(self.widget_14)
        self.comPortComboBox.setMinimumSize(QtCore.QSize(0, 0))
        self.comPortComboBox.setObjectName("comPortComboBox")
        self.horizontalLayout_14.addWidget(self.comPortComboBox)
        self.refreshSerialButton = QtWidgets.QPushButton(self.widget_14)
        self.refreshSerialButton.setObjectName("refreshSerialButton")
        self.horizontalLayout_14.addWidget(self.refreshSerialButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.horizontalLayout_13.addWidget(self.widget_14)
        self.verticalLayout_18.addWidget(self.widget_12)
        self.verticalLayout_9.addWidget(self.widget_15)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("img/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_2, icon3, "")
        self.verticalLayout_19.addWidget(self.tabWidget_2)
        self.verticalLayout_5.addWidget(self.connectionConfigWidget)
        self.line_3 = QtWidgets.QFrame(self.configPage)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_5.addWidget(self.line_3)
        self.line_2 = QtWidgets.QFrame(self.configPage)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.vectorGenTab = QtWidgets.QTabWidget(self.configPage)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.vectorGenTab.setFont(font)
        self.vectorGenTab.setObjectName("vectorGenTab")
        self.rohdeTab = QtWidgets.QWidget()
        self.rohdeTab.setObjectName("rohdeTab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.rohdeTab)
        self.horizontalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.widget_4 = QtWidgets.QWidget(self.rohdeTab)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.rohdeIPLineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.rohdeIPLineEdit.setObjectName("rohdeIPLineEdit")
        self.horizontalLayout_7.addWidget(self.rohdeIPLineEdit)
        self.connectVectorGenButton = QtWidgets.QPushButton(self.widget_5)
        self.connectVectorGenButton.setMinimumSize(QtCore.QSize(100, 0))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("img/connect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectVectorGenButton.setIcon(icon4)
        self.connectVectorGenButton.setObjectName("connectVectorGenButton")
        self.horizontalLayout_7.addWidget(self.connectVectorGenButton)
        self.verticalLayout_11.addWidget(self.widget_5)
        self.widget_16 = QtWidgets.QWidget(self.widget_4)
        self.widget_16.setObjectName("widget_16")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.widget_16)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_13 = QtWidgets.QLabel(self.widget_16)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.frequencySpinBox = QtWidgets.QDoubleSpinBox(self.widget_16)
        self.frequencySpinBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.frequencySpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.frequencySpinBox.setDecimals(3)
        self.frequencySpinBox.setMinimum(1.0)
        self.frequencySpinBox.setMaximum(999.99)
        self.frequencySpinBox.setSingleStep(0.001)
        self.frequencySpinBox.setProperty("value", 401.635)
        self.frequencySpinBox.setObjectName("frequencySpinBox")
        self.horizontalLayout_16.addWidget(self.frequencySpinBox)
        self.label_14 = QtWidgets.QLabel(self.widget_16)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_16.addWidget(self.label_14)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem2)
        self.label_15 = QtWidgets.QLabel(self.widget_16)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.levelSpinBox = QtWidgets.QSpinBox(self.widget_16)
        self.levelSpinBox.setMinimum(-120)
        self.levelSpinBox.setMaximum(-60)
        self.levelSpinBox.setProperty("value", -108)
        self.levelSpinBox.setObjectName("levelSpinBox")
        self.horizontalLayout_16.addWidget(self.levelSpinBox)
        self.label_16 = QtWidgets.QLabel(self.widget_16)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem3)
        self.verticalLayout_11.addWidget(self.widget_16)
        self.widget_17 = QtWidgets.QWidget(self.widget_4)
        self.widget_17.setObjectName("widget_17")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.widget_17)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_19 = QtWidgets.QLabel(self.widget_17)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_17.addWidget(self.label_19)
        self.waveformFileLineEdit = QtWidgets.QLineEdit(self.widget_17)
        self.waveformFileLineEdit.setMinimumSize(QtCore.QSize(150, 0))
        self.waveformFileLineEdit.setObjectName("waveformFileLineEdit")
        self.horizontalLayout_17.addWidget(self.waveformFileLineEdit)
        self.loadWaveformButton = QtWidgets.QPushButton(self.widget_17)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("img/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadWaveformButton.setIcon(icon5)
        self.loadWaveformButton.setObjectName("loadWaveformButton")
        self.horizontalLayout_17.addWidget(self.loadWaveformButton)
        self.verticalLayout_11.addWidget(self.widget_17)
        self.widget_19 = QtWidgets.QWidget(self.widget_4)
        self.widget_19.setObjectName("widget_19")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_19)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.enableBasebandCheckBox = QtWidgets.QCheckBox(self.widget_19)
        self.enableBasebandCheckBox.setObjectName("enableBasebandCheckBox")
        self.horizontalLayout_19.addWidget(self.enableBasebandCheckBox)
        self.enableRFCheckBox = QtWidgets.QCheckBox(self.widget_19)
        self.enableRFCheckBox.setObjectName("enableRFCheckBox")
        self.horizontalLayout_19.addWidget(self.enableRFCheckBox)
        self.periodicCheckBox = QtWidgets.QCheckBox(self.widget_19)
        self.periodicCheckBox.setObjectName("periodicCheckBox")
        self.horizontalLayout_19.addWidget(self.periodicCheckBox)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.verticalLayout_11.addWidget(self.widget_19)
        self.runSignalButton = QtWidgets.QPushButton(self.widget_4)
        self.runSignalButton.setEnabled(False)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("img/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.runSignalButton.setIcon(icon6)
        self.runSignalButton.setObjectName("runSignalButton")
        self.verticalLayout_11.addWidget(self.runSignalButton)
        self.widget_18 = QtWidgets.QWidget(self.widget_4)
        self.widget_18.setObjectName("widget_18")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.widget_18)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_20 = QtWidgets.QLabel(self.widget_18)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_18.addWidget(self.label_20)
        self.vecGenStatusLabel = QtWidgets.QLabel(self.widget_18)
        self.vecGenStatusLabel.setObjectName("vecGenStatusLabel")
        self.horizontalLayout_18.addWidget(self.vecGenStatusLabel)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem5)
        self.verticalLayout_11.addWidget(self.widget_18)
        self.horizontalLayout_4.addWidget(self.widget_4)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("img/vec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vectorGenTab.addTab(self.rohdeTab, icon7, "")
        self.verticalLayout_5.addWidget(self.vectorGenTab)
        self.deviceConfigWidget = QtWidgets.QWidget(self.configPage)
        self.deviceConfigWidget.setMaximumSize(QtCore.QSize(16777215, 300))
        self.deviceConfigWidget.setObjectName("deviceConfigWidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.deviceConfigWidget)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(self.deviceConfigWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.widget_9 = QtWidgets.QWidget(self.tab)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_14.addItem(spacerItem6)
        self.label_18 = QtWidgets.QLabel(self.widget_9)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_14.addWidget(self.label_18)
        self.widget_3 = QtWidgets.QWidget(self.widget_9)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.rtcDateEdit = QtWidgets.QDateEdit(self.widget_2)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rtcDateEdit.setFont(font)
        self.rtcDateEdit.setCalendarPopup(True)
        self.rtcDateEdit.setDate(QtCore.QDate(2017, 1, 1))
        self.rtcDateEdit.setObjectName("rtcDateEdit")
        self.horizontalLayout_3.addWidget(self.rtcDateEdit)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_6.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.widget_3)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.rtcTimeEdit = QtWidgets.QTimeEdit(self.widget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.rtcTimeEdit.setFont(font)
        self.rtcTimeEdit.setCalendarPopup(False)
        self.rtcTimeEdit.setObjectName("rtcTimeEdit")
        self.horizontalLayout_2.addWidget(self.rtcTimeEdit)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.verticalLayout_6.addWidget(self.widget)
        self.setRTCButton = QtWidgets.QPushButton(self.widget_3)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.setRTCButton.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("img/play3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setRTCButton.setIcon(icon8)
        self.setRTCButton.setObjectName("setRTCButton")
        self.verticalLayout_6.addWidget(self.setRTCButton)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pauseRTCButton = QtWidgets.QPushButton(self.widget_6)
        self.pauseRTCButton.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("img/rtc_pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseRTCButton.setIcon(icon9)
        self.pauseRTCButton.setObjectName("pauseRTCButton")
        self.horizontalLayout_5.addWidget(self.pauseRTCButton)
        self.resumeRTCButton = QtWidgets.QPushButton(self.widget_6)
        self.resumeRTCButton.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("img/rtc_play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resumeRTCButton.setIcon(icon10)
        self.resumeRTCButton.setObjectName("resumeRTCButton")
        self.horizontalLayout_5.addWidget(self.resumeRTCButton)
        self.resetRTCButton = QtWidgets.QPushButton(self.widget_6)
        self.resetRTCButton.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("img/rtc_reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.resetRTCButton.setIcon(icon11)
        self.resetRTCButton.setObjectName("resetRTCButton")
        self.horizontalLayout_5.addWidget(self.resetRTCButton)
        self.verticalLayout_6.addWidget(self.widget_6)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.verticalLayout_14.addWidget(self.widget_3)
        self.verticalLayout_13.addWidget(self.widget_9)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("img/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon12, "")
        self.horizontalLayout_8.addWidget(self.tabWidget)
        self.tabWidget_3 = QtWidgets.QTabWidget(self.deviceConfigWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget_3.setFont(font)
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_hk = QtWidgets.QWidget()
        self.tab_hk.setMinimumSize(QtCore.QSize(168, 0))
        self.tab_hk.setObjectName("tab_hk")
        self.widget_20 = QtWidgets.QWidget(self.tab_hk)
        self.widget_20.setGeometry(QtCore.QRect(1, -2, 161, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_20.sizePolicy().hasHeightForWidth())
        self.widget_20.setSizePolicy(sizePolicy)
        self.widget_20.setMinimumSize(QtCore.QSize(151, 179))
        self.widget_20.setObjectName("widget_20")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_20)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.widget_13 = QtWidgets.QWidget(self.widget_20)
        self.widget_13.setObjectName("widget_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_13)
        self.horizontalLayout_10.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_17 = QtWidgets.QLabel(self.widget_13)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_10.addWidget(self.label_17)
        self.hkRequestSpinBox = QtWidgets.QSpinBox(self.widget_13)
        self.hkRequestSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.hkRequestSpinBox.setMinimum(1)
        self.hkRequestSpinBox.setObjectName("hkRequestSpinBox")
        self.horizontalLayout_10.addWidget(self.hkRequestSpinBox)
        self.verticalLayout_10.addWidget(self.widget_13)
        self.groupBox = QtWidgets.QGroupBox(self.widget_20)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(5, 9, 0, 9)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 8, 0, 1, 1)
        self.hkRTCCheck = QtWidgets.QCheckBox(self.groupBox)
        self.hkRTCCheck.setText("")
        self.hkRTCCheck.setChecked(True)
        self.hkRTCCheck.setObjectName("hkRTCCheck")
        self.gridLayout.addWidget(self.hkRTCCheck, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 5, 0, 1, 1)
        self.hkCurrentSensorCheck = QtWidgets.QCheckBox(self.groupBox)
        self.hkCurrentSensorCheck.setText("")
        self.hkCurrentSensorCheck.setChecked(True)
        self.hkCurrentSensorCheck.setObjectName("hkCurrentSensorCheck")
        self.gridLayout.addWidget(self.hkCurrentSensorCheck, 2, 2, 1, 1)
        self.hkOverCurrentErrorCheck = QtWidgets.QCheckBox(self.groupBox)
        self.hkOverCurrentErrorCheck.setText("")
        self.hkOverCurrentErrorCheck.setChecked(True)
        self.hkOverCurrentErrorCheck.setObjectName("hkOverCurrentErrorCheck")
        self.gridLayout.addWidget(self.hkOverCurrentErrorCheck, 8, 2, 1, 1)
        self.hkADCRmsCheck = QtWidgets.QCheckBox(self.groupBox)
        self.hkADCRmsCheck.setText("")
        self.hkADCRmsCheck.setChecked(True)
        self.hkADCRmsCheck.setObjectName("hkADCRmsCheck")
        self.gridLayout.addWidget(self.hkADCRmsCheck, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.hkPLLSyncBitCheck = QtWidgets.QCheckBox(self.groupBox)
        self.hkPLLSyncBitCheck.setText("")
        self.hkPLLSyncBitCheck.setChecked(True)
        self.hkPLLSyncBitCheck.setObjectName("hkPLLSyncBitCheck")
        self.gridLayout.addWidget(self.hkPLLSyncBitCheck, 5, 2, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox)
        self.updateHKButton = QtWidgets.QPushButton(self.widget_20)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.updateHKButton.setFont(font)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("img/check.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.updateHKButton.setIcon(icon13)
        self.updateHKButton.setObjectName("updateHKButton")
        self.verticalLayout_10.addWidget(self.updateHKButton)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem11)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("img/stats.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_hk, icon14, "HouseKeeping")
        self.horizontalLayout_8.addWidget(self.tabWidget_3)
        self.verticalLayout_5.addWidget(self.deviceConfigWidget)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem12)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("img/config.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlToolBox.addItem(self.configPage, icon15, "")
        self.measurePage = QtWidgets.QWidget()
        self.measurePage.setGeometry(QtCore.QRect(0, 0, 398, 641))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.measurePage.setFont(font)
        self.measurePage.setObjectName("measurePage")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.measurePage)
        self.verticalLayout_8.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.chartWidget = QtWidgets.QWidget(self.measurePage)
        self.chartWidget.setStyleSheet("")
        self.chartWidget.setObjectName("chartWidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.chartWidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.chartWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.chartCanvasWidget_0 = QtWidgets.QWidget(self.chartWidget)
        self.chartCanvasWidget_0.setMinimumSize(QtCore.QSize(100, 150))
        self.chartCanvasWidget_0.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.chartCanvasWidget_0.setAutoFillBackground(False)
        self.chartCanvasWidget_0.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.chartCanvasWidget_0.setObjectName("chartCanvasWidget_0")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.chartCanvasWidget_0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.verticalLayout_7.addWidget(self.chartCanvasWidget_0)
        self.label_10 = QtWidgets.QLabel(self.chartWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_7.addWidget(self.label_10)
        self.chartCanvasWidget_1 = QtWidgets.QWidget(self.chartWidget)
        self.chartCanvasWidget_1.setMinimumSize(QtCore.QSize(100, 150))
        self.chartCanvasWidget_1.setStyleSheet("background-color: rgb(61, 61, 61);")
        self.chartCanvasWidget_1.setObjectName("chartCanvasWidget_1")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.chartCanvasWidget_1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.verticalLayout_7.addWidget(self.chartCanvasWidget_1)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem13)
        self.verticalLayout_8.addWidget(self.chartWidget)
        self.controlToolBox.addItem(self.measurePage, icon14, "")
        self.consolePage = QtWidgets.QWidget()
        self.consolePage.setGeometry(QtCore.QRect(0, 0, 398, 641))
        self.consolePage.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.consolePage.setObjectName("consolePage")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.consolePage)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.line_7 = QtWidgets.QFrame(self.consolePage)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout_12.addWidget(self.line_7)
        self.widget_7 = QtWidgets.QWidget(self.consolePage)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.widget_7.setFont(font)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_8 = QtWidgets.QWidget(self.widget_7)
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_8)
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.enableConsoleCheckBox = QtWidgets.QCheckBox(self.widget_8)
        self.enableConsoleCheckBox.setObjectName("enableConsoleCheckBox")
        self.horizontalLayout_15.addWidget(self.enableConsoleCheckBox)
        self.label_11 = QtWidgets.QLabel(self.widget_8)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_15.addWidget(self.label_11)
        self.serialConsoleComboBox = QtWidgets.QComboBox(self.widget_8)
        self.serialConsoleComboBox.setObjectName("serialConsoleComboBox")
        self.horizontalLayout_15.addWidget(self.serialConsoleComboBox)
        self.refreshSerialButton2 = QtWidgets.QPushButton(self.widget_8)
        self.refreshSerialButton2.setObjectName("refreshSerialButton2")
        self.horizontalLayout_15.addWidget(self.refreshSerialButton2)
        self.clearConsoleButton = QtWidgets.QPushButton(self.widget_8)
        self.clearConsoleButton.setObjectName("clearConsoleButton")
        self.horizontalLayout_15.addWidget(self.clearConsoleButton)
        self.verticalLayout_16.addWidget(self.widget_8)
        self.consoleTextEdit = QtWidgets.QTextEdit(self.widget_7)
        self.consoleTextEdit.setMinimumSize(QtCore.QSize(0, 230))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.consoleTextEdit.setFont(font)
        self.consoleTextEdit.setAutoFillBackground(False)
        self.consoleTextEdit.setStyleSheet("background-color: rgb(179, 179, 179);")
        self.consoleTextEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.consoleTextEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.consoleTextEdit.setUndoRedoEnabled(False)
        self.consoleTextEdit.setReadOnly(True)
        self.consoleTextEdit.setAcceptRichText(True)
        self.consoleTextEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.consoleTextEdit.setObjectName("consoleTextEdit")
        self.verticalLayout_16.addWidget(self.consoleTextEdit)
        self.widget_10 = QtWidgets.QWidget(self.widget_7)
        self.widget_10.setObjectName("widget_10")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.widget_10)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_12 = QtWidgets.QLabel(self.widget_10)
        self.label_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_17.addWidget(self.label_12)
        self.verticalLayout_16.addWidget(self.widget_10)
        self.line_6 = QtWidgets.QFrame(self.widget_7)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_16.addWidget(self.line_6)
        self.verticalLayout_12.addWidget(self.widget_7)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("img/console.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.controlToolBox.addItem(self.consolePage, icon16, "")
        self.verticalLayout_15.addWidget(self.controlToolBox)
        self.horizontalLayout.addWidget(self.widget_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1088, 20))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setEnabled(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setIcon(icon5)
        self.actionOpen.setObjectName("actionOpen")
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("img/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon17)
        self.actionNew.setObjectName("actionNew")
        self.actionPlay = QtWidgets.QAction(MainWindow)
        self.actionPlay.setEnabled(False)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("img/play4.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPlay.setIcon(icon18)
        self.actionPlay.setObjectName("actionPlay")
        self.actionPause = QtWidgets.QAction(MainWindow)
        self.actionPause.setEnabled(False)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("img/pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon19)
        self.actionPause.setObjectName("actionPause")
        self.actionStop = QtWidgets.QAction(MainWindow)
        self.actionStop.setEnabled(False)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("img/stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon20)
        self.actionStop.setObjectName("actionStop")
        self.actionEchoTest = QtWidgets.QAction(MainWindow)
        self.actionEchoTest.setEnabled(False)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("img/echo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEchoTest.setIcon(icon21)
        self.actionEchoTest.setObjectName("actionEchoTest")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setEnabled(False)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("img/clear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionClear.setIcon(icon22)
        self.actionClear.setObjectName("actionClear")
        self.actionConnect = QtWidgets.QAction(MainWindow)
        self.actionConnect.setIcon(icon4)
        self.actionConnect.setObjectName("actionConnect")
        self.actionDisconnect = QtWidgets.QAction(MainWindow)
        self.actionDisconnect.setEnabled(False)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("img/disconnect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDisconnect.setIcon(icon23)
        self.actionDisconnect.setObjectName("actionDisconnect")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("img/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon24)
        self.actionSave.setObjectName("actionSave")
        self.actionStartServer = QtWidgets.QAction(MainWindow)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("img/server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStartServer.setIcon(icon25)
        self.actionStartServer.setObjectName("actionStartServer")
        self.actionStopServer = QtWidgets.QAction(MainWindow)
        self.actionStopServer.setEnabled(False)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("img/stop_server.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStopServer.setIcon(icon26)
        self.actionStopServer.setObjectName("actionStopServer")
        self.actionADCSampler = QtWidgets.QAction(MainWindow)
        self.actionADCSampler.setEnabled(False)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("img/adc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionADCSampler.setIcon(icon27)
        self.actionADCSampler.setObjectName("actionADCSampler")
        self.actionToneGenerator = QtWidgets.QAction(MainWindow)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("img/sine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionToneGenerator.setIcon(icon28)
        self.actionToneGenerator.setObjectName("actionToneGenerator")
        self.menuRun.addAction(self.actionPlay)
        self.menuRun.addAction(self.actionPause)
        self.menuRun.addAction(self.actionStop)
        self.menuRun.addAction(self.actionClear)
        self.menuTools.addAction(self.actionEchoTest)
        self.menuTools.addAction(self.actionADCSampler)
        self.menuTools.addAction(self.actionToneGenerator)
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionConnect)
        self.toolBar.addAction(self.actionDisconnect)
        self.toolBar.addAction(self.actionADCSampler)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addAction(self.actionPlay)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionClear)

        self.retranslateUi(MainWindow)
        self.detailToolBox.setCurrentIndex(0)
        self.detailToolBox.layout().setSpacing(0)
        self.controlToolBox.setCurrentIndex(0)
        self.controlToolBox.layout().setSpacing(0)
        self.tabWidget_2.setCurrentIndex(0)
        self.vectorGenTab.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DCS Controller"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Filter Packages:"))
        self.filterWidget.setToolTip(_translate("MainWindow", "Select the type of package to be read and displayed"))
        self.filterPTTCheckBox.setText(_translate("MainWindow", "PTT"))
        self.filterHKCheckBox.setText(_translate("MainWindow", "House Keeping"))
        item = self.mainTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "No."))
        item = self.mainTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.mainTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Timestamp"))
        item = self.mainTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Info"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Field"))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "Value"))
        self.detailToolBox.setItemText(self.detailToolBox.indexOf(self.detailPackageBox), _translate("MainWindow", "Package Detail"))
        item = self.rawDataTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Byte"))
        item = self.rawDataTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hex"))
        item = self.rawDataTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ASCII"))
        self.detailToolBox.setItemText(self.detailToolBox.indexOf(self.rawDataBox), _translate("MainWindow", "Raw Data"))
        self.connSerialRadio.setText(_translate("MainWindow", "Arduino"))
        self.connFtdiRadio.setText(_translate("MainWindow", "FTDI"))
        self.refreshSerialButton.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("MainWindow", "Connection"))
        self.label.setText(_translate("MainWindow", "IP Address:"))
        self.rohdeIPLineEdit.setText(_translate("MainWindow", "200.137.4.218"))
        self.connectVectorGenButton.setText(_translate("MainWindow", "Connect"))
        self.label_13.setText(_translate("MainWindow", "Frequency:"))
        self.label_14.setText(_translate("MainWindow", "MHz"))
        self.label_15.setText(_translate("MainWindow", "Level: "))
        self.label_16.setText(_translate("MainWindow", "dBm"))
        self.label_19.setText(_translate("MainWindow", "File:"))
        self.waveformFileLineEdit.setText(_translate("MainWindow", "waveform.wv"))
        self.loadWaveformButton.setText(_translate("MainWindow", "Load Waveform"))
        self.enableBasebandCheckBox.setText(_translate("MainWindow", "Enable Baseband"))
        self.enableRFCheckBox.setText(_translate("MainWindow", "Enable RF/A"))
        self.periodicCheckBox.setText(_translate("MainWindow", "Single Shot"))
        self.runSignalButton.setText(_translate("MainWindow", "Trigger"))
        self.label_20.setText(_translate("MainWindow", "Status:"))
        self.vecGenStatusLabel.setText(_translate("MainWindow", "Vector Generator disconnected."))
        self.vectorGenTab.setTabText(self.vectorGenTab.indexOf(self.rohdeTab), _translate("MainWindow", "Vector Generator"))
        self.label_18.setText(_translate("MainWindow", "RTC Configuration"))
        self.label_2.setText(_translate("MainWindow", "Date:"))
        self.rtcDateEdit.setDisplayFormat(_translate("MainWindow", "dd/MM/yyyy"))
        self.label_3.setText(_translate("MainWindow", "Time:"))
        self.setRTCButton.setText(_translate("MainWindow", "Set RTC Time"))
        self.pauseRTCButton.setToolTip(_translate("MainWindow", "Pause RTC"))
        self.resumeRTCButton.setToolTip(_translate("MainWindow", "Resume RTC"))
        self.resetRTCButton.setToolTip(_translate("MainWindow", "Reset RTC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "RTC"))
        self.label_17.setText(_translate("MainWindow", "Request Time (s):"))
        self.groupBox.setToolTip(_translate("MainWindow", "Select measures for housekeeping packages"))
        self.groupBox.setTitle(_translate("MainWindow", "Housekeeping Flags: "))
        self.label_8.setText(_translate("MainWindow", "Over Current"))
        self.label_6.setText(_translate("MainWindow", "ADC RMS"))
        self.label_7.setText(_translate("MainWindow", "PLL Sync Bit"))
        self.label_4.setText(_translate("MainWindow", "RTC:"))
        self.label_5.setText(_translate("MainWindow", "Current Sensors:"))
        self.updateHKButton.setText(_translate("MainWindow", "Update HK Settings"))
        self.controlToolBox.setItemText(self.controlToolBox.indexOf(self.configPage), _translate("MainWindow", "Configuration"))
        self.label_9.setText(_translate("MainWindow", "ADC RMS Values:"))
        self.label_10.setText(_translate("MainWindow", "Current Sensors:"))
        self.controlToolBox.setItemText(self.controlToolBox.indexOf(self.measurePage), _translate("MainWindow", "Measures"))
        self.enableConsoleCheckBox.setText(_translate("MainWindow", "Enable"))
        self.label_11.setText(_translate("MainWindow", "COM:"))
        self.refreshSerialButton2.setText(_translate("MainWindow", "Refresh"))
        self.clearConsoleButton.setText(_translate("MainWindow", "Clear"))
        self.consoleTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "Serial UART Console (115200 baud)"))
        self.controlToolBox.setItemText(self.controlToolBox.indexOf(self.consolePage), _translate("MainWindow", "Console"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionQuit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setToolTip(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setToolTip(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionPlay.setText(_translate("MainWindow", "Play"))
        self.actionPlay.setToolTip(_translate("MainWindow", "Start Reading Packages"))
        self.actionPause.setText(_translate("MainWindow", "Pause"))
        self.actionPause.setToolTip(_translate("MainWindow", "Pause Reading Packages"))
        self.actionStop.setText(_translate("MainWindow", "Stop"))
        self.actionStop.setToolTip(_translate("MainWindow", "Stop and Clear Package Reading"))
        self.actionEchoTest.setText(_translate("MainWindow", "Echo Test"))
        self.actionEchoTest.setToolTip(_translate("MainWindow", "Sends an Echo Command"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionClear.setToolTip(_translate("MainWindow", "Clears the Package List"))
        self.actionConnect.setText(_translate("MainWindow", "Connect"))
        self.actionConnect.setToolTip(_translate("MainWindow", "Connect Device"))
        self.actionConnect.setShortcut(_translate("MainWindow", "Ctrl+Shift+C"))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect"))
        self.actionDisconnect.setToolTip(_translate("MainWindow", "Disconnect Device"))
        self.actionDisconnect.setShortcut(_translate("MainWindow", "Ctrl+Shift+D"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setToolTip(_translate("MainWindow", "Saves Package List to a File"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionStartServer.setText(_translate("MainWindow", "Start I2C Network Server"))
        self.actionStartServer.setToolTip(_translate("MainWindow", "Starts I2C bridge server on Raspberry Pi"))
        self.actionStopServer.setText(_translate("MainWindow", "Stop I2C Network Server"))
        self.actionStopServer.setToolTip(_translate("MainWindow", "Stops the I2C bridge server"))
        self.actionADCSampler.setText(_translate("MainWindow", "ADC Sampler"))
        self.actionADCSampler.setStatusTip(_translate("MainWindow", "ADC Sampler Window"))
        self.actionADCSampler.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.actionToneGenerator.setText(_translate("MainWindow", "Tone Generator"))
        self.actionToneGenerator.setShortcut(_translate("MainWindow", "Ctrl+W"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

